language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t abrahamjkwan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true abrahamjkwan/react-test npm test

after_success:
  - docker build -t abrahamjkwan/multi-client ./client
  - docker build -t abrahamjkwan/multi-nginx ./nginx
  - docker build -t abrahamjkwan/multi-server ./server
  - docker build -t abrahamjkwan/multi-worker ./worker
  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take images and push them to Docker Hub
  - docker push abrahamjkwan/multi-client
  - docker push abrahamjkwan/multi-nginx
  - docker push abrahamjkwan/multi-server
  - docker push abrahamjkwan/multi-worker


  deploy:
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-us-west-2-775191751512"
    bucket_path: "docker-multi"
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY